baseURL = "https://burak.dev"
title = "Burak Keskin"
copyright = "Copyright © 2020, Burak Keskin, all rights reserved."
paginate = 2
languageCode = "tr"
DefaultContentLanguage = "tr"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Anasayfa"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Hakkımda"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Burak Keskin"
  share = true
#   showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "me@burak.dev"
    twitter = "https://twitter.com/keskinbu"
    linkedin = "https://linkedin.com/in/burakkeskin"
    # stack-overflow = "https://stackoverflow.com"
    # instagram = "https://stackoverflow.com"
    github = "https://github.com/keskinbu"
    # weibo = "https://www.weibo.com"
    medium = "https://medium.com/@burak.keskin"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
